In [28]:
import numpy as np
import matplotlib.pyplot as plt

In [29]:
n = 100
apple_width = np.random.normal(6, 1, n) 
apple_length = np.random.normal(6, 1, n)

banana_width = np.random.normal(4, 1, n)
banana_length = np.random.normal(8, 1, n)

Watermelon_width = np.random.normal(20, 3, n)
Watermelon_length = np.random.normal(20, 3, n)

In [30]:
width = np.concatenate((apple_width, banana_width, Watermelon_width))
length = np.concatenate((apple_length, banana_length, Watermelon_length))

X_train = np.array([width, length]).T
X_train

array([[ 7.28775887,  5.37548186],
       [ 6.54204991,  5.89173623],
       [ 6.07670515,  4.73190583],
       [ 7.88218164,  6.66365401],
       [ 5.25810809,  7.06450147],
       [ 6.50610324,  6.07913388],
       [ 7.03774642,  6.0139731 ],
       [ 8.09194964,  6.15739529],
       [ 5.38035596,  4.7043207 ],
       [ 5.24684444,  6.59468972],
       [ 6.04045087,  4.6926111 ],
       [ 5.47244926,  4.19969414],
       [ 5.90394325,  6.49986737],
       [ 5.53453792,  5.11695088],
       [ 6.60837935,  7.69697293],
       [ 5.8869965 ,  6.49066743],
       [ 6.42236098,  7.89461134],
       [ 5.26392874,  5.33579356],
       [ 6.47567215,  6.49514814],
       [ 4.6923905 ,  5.88513688],
       [ 5.94844974,  5.28416481],
       [ 6.09388447,  3.38671151],
       [ 6.2132916 ,  6.02886108],
       [ 5.51618882,  5.64079171],
       [ 4.23437238,  7.3029647 ],
       [ 6.24405767,  5.76714302],
       [ 6.11486701,  6.00004777],
       [ 5.67007056,  5.43814441],
       [ 5.71091438,

In [31]:
Y_apples = np.zeros(n, dtype='int')   
Y_bananas = np.ones(n, dtype='int')
Y_Watermelon = np.ones(n, dtype='int')*2

Y_train = np.concatenate((Y_apples, Y_bananas, Y_Watermelon))
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
new_fruit = np.array([18, 21]) 

In [41]:
def euclidean_distance(x1, x2):  
    return np.sqrt(np.sum((x1 - x2)**2))

In [42]:
distances =[]  
for x in X_train:
   d = euclidean_distance(new_fruit, x)
   distances.append(d)

distances

[18.944067074373763,
 18.961652206561016,
 20.16967644422482,
 17.5471098710889,
 18.88263563765782,
 18.834593396535602,
 18.56749863899494,
 17.845794364173027,
 20.61078793914704,
 19.239437131046415,
 20.222802675825914,
 20.95685578959562,
 18.883019761532147,
 20.190566961722613,
 17.513981567878474,
 18.900941394157243,
 17.486936182269215,
 20.188483704937507,
 18.525681085921907,
 20.138310693151038,
 19.804730223483542,
 21.259904007415884,
 19.054172657316546,
 19.792696151149016,
 19.419095748686086,
 19.241676429893506,
 19.137788619251193,
 19.85443299278651,
 20.291613748478255,
 18.578656138411468,
 19.65049667943217,
 19.287814823787752,
 19.854401189577768,
 19.030733123720655,
 20.200430744594648,
 17.79011792608749,
 20.094466663873238,
 20.108553328255958,
 18.818756836416636,
 18.492986298078026,
 19.92008189005013,
 18.105624265955093,
 18.959251852436,
 19.54290330412607,
 20.095886362421474,
 19.38991499816785,
 19.335262640897824,
 20.613942826351796,
 18.0224

In [43]:
k = 7

In [44]:
nearest_neighbors  = np.argsort(distances)[0:k]  

nearest_neighbors

array([209, 282, 270, 277, 261, 266, 252], dtype=int64)

In [45]:
Y_train[nearest_neighbors]

array([2, 2, 2, 2, 2, 2, 2])

In [46]:
result = np.bincount(Y_train[nearest_neighbors])
result

array([0, 0, 7], dtype=int64)

In [47]:
if np.argmax(result) == 0:
    print("Apple 🍎")
elif np.argmax(result) == 1:
    print("Banana 🍌")   
else:
    print("Watermelon 🍉")   

Watermelon 🍉
